var classes = [
    {
        "name": "App\\Http\\Controllers\\Admin\\ManageUserController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 8,
        "ccnMethodMax": 7,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\User",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\Models\\User",
            "App\\Models\\Dokter",
            "App\\Models\\User",
            "Illuminate\\Http\\Request",
            "App\\Models\\User",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\Models\\Dokter",
            "App\\Models\\User"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 7,
        "length": 185,
        "vocabulary": 48,
        "volume": 1033.22,
        "difficulty": 11.36,
        "effort": 11734.41,
        "level": 0.09,
        "bugs": 0.34,
        "time": 652,
        "intelligentContent": 90.98,
        "number_operators": 26,
        "number_operands": 159,
        "number_operators_unique": 6,
        "number_operands_unique": 42,
        "cloc": 25,
        "loc": 86,
        "lloc": 61,
        "mi": 75.95,
        "mIwoC": 38.87,
        "commentWeight": 37.07,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.43,
        "relativeSystemComplexity": 225.43,
        "totalStructuralComplexity": 1575,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 1578,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\AuthenticatedSessionController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\Auth\\LoginRequest",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 13,
        "vocabulary": 6,
        "volume": 33.6,
        "difficulty": 1,
        "effort": 33.6,
        "level": 1,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 33.6,
        "number_operators": 3,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 9,
        "loc": 30,
        "lloc": 21,
        "mi": 97.85,
        "mIwoC": 60.34,
        "commentWeight": 37.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.41,
        "relativeSystemComplexity": 64.41,
        "totalStructuralComplexity": 192,
        "totalDataComplexity": 1.22,
        "totalSystemComplexity": 193.22,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\ConfirmablePasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Validation\\ValidationException"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 15,
        "vocabulary": 10,
        "volume": 49.83,
        "difficulty": 1.5,
        "effort": 74.74,
        "level": 0.67,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 33.22,
        "number_operators": 3,
        "number_operands": 12,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 6,
        "loc": 22,
        "lloc": 16,
        "mi": 97.76,
        "mIwoC": 61.58,
        "commentWeight": 36.18,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.31,
        "relativeSystemComplexity": 49.31,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0.63,
        "totalSystemComplexity": 98.63,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\EmailVerificationNotificationController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 1.5,
        "effort": 34.9,
        "level": 0.67,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 15.51,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 15,
        "lloc": 12,
        "mi": 98.56,
        "mIwoC": 66.62,
        "commentWeight": 31.94,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 25.5,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\EmailVerificationPromptController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0.67,
        "effort": 6.67,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 15,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 109.21,
        "mIwoC": 73.03,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 9.5,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\NewPasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Support\\Str",
            "Illuminate\\Auth\\Events\\PasswordReset",
            "Illuminate\\Support\\Facades\\Password"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 40,
        "vocabulary": 16,
        "volume": 160,
        "difficulty": 4.15,
        "effort": 664.62,
        "level": 0.24,
        "bugs": 0.05,
        "time": 37,
        "intelligentContent": 38.52,
        "number_operators": 4,
        "number_operands": 36,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 14,
        "loc": 31,
        "lloc": 17,
        "mi": 100.6,
        "mIwoC": 57.46,
        "commentWeight": 43.15,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.23,
        "relativeSystemComplexity": 144.23,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 0.46,
        "totalSystemComplexity": 288.46,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\PasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 18,
        "vocabulary": 11,
        "volume": 62.27,
        "difficulty": 1.78,
        "effort": 110.7,
        "level": 0.56,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 35.03,
        "number_operators": 2,
        "number_operands": 16,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 3,
        "loc": 13,
        "lloc": 10,
        "mi": 99.36,
        "mIwoC": 65.49,
        "commentWeight": 33.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.29,
        "totalSystemComplexity": 36.29,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\PasswordResetLinkController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Password"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 20,
        "vocabulary": 8,
        "volume": 60,
        "difficulty": 4.8,
        "effort": 288,
        "level": 0.21,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 12.5,
        "number_operators": 4,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 11,
        "loc": 25,
        "lloc": 14,
        "mi": 105.08,
        "mIwoC": 62.28,
        "commentWeight": 42.8,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.36,
        "relativeSystemComplexity": 36.36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.71,
        "totalSystemComplexity": 72.71,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\RegisteredUserController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\Models\\User",
            "Illuminate\\Auth\\Events\\Registered",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 37,
        "vocabulary": 18,
        "volume": 154.29,
        "difficulty": 3.3,
        "effort": 509.15,
        "level": 0.3,
        "bugs": 0.05,
        "time": 28,
        "intelligentContent": 46.75,
        "number_operators": 4,
        "number_operands": 33,
        "number_operators_unique": 3,
        "number_operands_unique": 15,
        "cloc": 8,
        "loc": 24,
        "lloc": 16,
        "mi": 97.27,
        "mIwoC": 58.28,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 25.42,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 50.83,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\VerifyEmailController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Foundation\\Auth\\EmailVerificationRequest",
            "Illuminate\\Auth\\Events\\Verified"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 6,
        "volume": 36.19,
        "difficulty": 4,
        "effort": 144.76,
        "level": 0.25,
        "bugs": 0.01,
        "time": 8,
        "intelligentContent": 9.05,
        "number_operators": 6,
        "number_operands": 8,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 3,
        "loc": 17,
        "lloc": 14,
        "mi": 93.97,
        "mIwoC": 63.68,
        "commentWeight": 30.29,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.6,
        "totalSystemComplexity": 16.6,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\BookingKonsultasiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "manage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showCompleteForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "complete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Hewan",
            "App\\Models\\User",
            "Illuminate\\Http\\Request",
            "App\\Models\\Hewan",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\BookingKonsultasi",
            "App\\Models\\BookingKonsultasi",
            "Illuminate\\Http\\Request",
            "App\\Models\\BookingKonsultasi",
            "App\\Models\\BookingKonsultasi",
            "App\\Models\\Hewan",
            "App\\Models\\Dokter",
            "Illuminate\\Http\\Request",
            "App\\Models\\BookingKonsultasi",
            "App\\Models\\Hewan",
            "App\\Models\\Dokter",
            "App\\Models\\RekamMedis"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 6,
        "length": 164,
        "vocabulary": 61,
        "volume": 972.64,
        "difficulty": 7.15,
        "effort": 6949.96,
        "level": 0.14,
        "bugs": 0.32,
        "time": 386,
        "intelligentContent": 136.12,
        "number_operators": 33,
        "number_operands": 131,
        "number_operators_unique": 6,
        "number_operands_unique": 55,
        "cloc": 19,
        "loc": 87,
        "lloc": 68,
        "mi": 71.28,
        "mIwoC": 38.16,
        "commentWeight": 33.12,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 961,
        "relativeDataComplexity": 0.34,
        "relativeSystemComplexity": 961.34,
        "totalStructuralComplexity": 5766,
        "totalDataComplexity": 2.06,
        "totalSystemComplexity": 5768.06,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 5,
        "lloc": 4,
        "mi": 202.94,
        "mIwoC": 171,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.22,
        "afferentCoupling": 21,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\DashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "setPet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Hewan",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\User",
            "App\\Models\\Hewan",
            "App\\Models\\BookingKonsultasi",
            "App\\Models\\PenitipanHewan",
            "App\\Models\\User",
            "App\\Models\\Hewan",
            "App\\Models\\BookingKonsultasi"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 68,
        "vocabulary": 34,
        "volume": 345.95,
        "difficulty": 3.67,
        "effort": 1268.47,
        "level": 0.27,
        "bugs": 0.12,
        "time": 70,
        "intelligentContent": 94.35,
        "number_operators": 13,
        "number_operands": 55,
        "number_operators_unique": 4,
        "number_operands_unique": 30,
        "cloc": 12,
        "loc": 37,
        "lloc": 25,
        "mi": 89.8,
        "mIwoC": 51.19,
        "commentWeight": 38.61,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 576,
        "relativeDataComplexity": 0.18,
        "relativeSystemComplexity": 576.18,
        "totalStructuralComplexity": 1152,
        "totalDataComplexity": 0.36,
        "totalSystemComplexity": 1152.36,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\DokterController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Dokter",
            "App\\Models\\Dokter",
            "Illuminate\\Http\\Request",
            "App\\Models\\Dokter",
            "App\\Models\\Dokter"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 7,
        "length": 6,
        "vocabulary": 2,
        "volume": 6,
        "difficulty": 0,
        "effort": 0,
        "level": 0.67,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 28,
        "loc": 53,
        "lloc": 25,
        "mi": 109.06,
        "mIwoC": 63.92,
        "commentWeight": 45.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0.86,
        "relativeSystemComplexity": 0.86,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\GroqbotController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "chat",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Http"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 97,
        "vocabulary": 47,
        "volume": 538.8,
        "difficulty": 5.12,
        "effort": 2759.68,
        "level": 0.2,
        "bugs": 0.18,
        "time": 153,
        "intelligentContent": 105.19,
        "number_operators": 27,
        "number_operands": 70,
        "number_operators_unique": 6,
        "number_operands_unique": 41,
        "cloc": 9,
        "loc": 52,
        "lloc": 43,
        "mi": 74.34,
        "mIwoC": 44.3,
        "commentWeight": 30.04,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.72,
        "relativeSystemComplexity": 64.72,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 1.44,
        "totalSystemComplexity": 129.44,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\HewanController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 5,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Hewan",
            "App\\Models\\Hewan",
            "App\\Models\\User",
            "Illuminate\\Http\\Request",
            "App\\Models\\Hewan",
            "App\\Models\\Hewan",
            "App\\Models\\Hewan",
            "App\\Models\\User",
            "Illuminate\\Http\\Request",
            "App\\Models\\Hewan",
            "App\\Models\\Hewan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 7,
        "length": 148,
        "vocabulary": 48,
        "volume": 826.57,
        "difficulty": 5.5,
        "effort": 4546.16,
        "level": 0.18,
        "bugs": 0.28,
        "time": 253,
        "intelligentContent": 150.29,
        "number_operators": 27,
        "number_operands": 121,
        "number_operators_unique": 4,
        "number_operands_unique": 44,
        "cloc": 31,
        "loc": 94,
        "lloc": 63,
        "mi": 78.49,
        "mIwoC": 39.65,
        "commentWeight": 38.84,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.39,
        "relativeSystemComplexity": 361.39,
        "totalStructuralComplexity": 2527,
        "totalDataComplexity": 2.75,
        "totalSystemComplexity": 2529.75,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\HomeController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 1.33,
        "effort": 18.58,
        "level": 0.75,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 10.45,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 9,
        "lloc": 9,
        "mi": 71.04,
        "mIwoC": 71.04,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\LayananController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "indexBooking",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "indexKonsultasi",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "indexRawatJalan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Layanan",
            "App\\Models\\Layanan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Layanan",
            "App\\Models\\Layanan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 10,
        "length": 12,
        "vocabulary": 6,
        "volume": 31.02,
        "difficulty": 2.5,
        "effort": 77.55,
        "level": 0.4,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 12.41,
        "number_operators": 2,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 30,
        "loc": 66,
        "lloc": 36,
        "mi": 98.7,
        "mIwoC": 55.47,
        "commentWeight": 43.23,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.6,
        "relativeSystemComplexity": 1.6,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 16,
        "totalSystemComplexity": 16,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\PemeriksaanLabController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "manage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Hewan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Hewan",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\PemeriksaanLab",
            "App\\Models\\PemeriksaanLab",
            "Illuminate\\Http\\Request",
            "App\\Models\\PemeriksaanLab"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 91,
        "vocabulary": 46,
        "volume": 502.64,
        "difficulty": 5.48,
        "effort": 2751.98,
        "level": 0.18,
        "bugs": 0.17,
        "time": 153,
        "intelligentContent": 91.81,
        "number_operators": 18,
        "number_operands": 73,
        "number_operators_unique": 6,
        "number_operands_unique": 40,
        "cloc": 8,
        "loc": 51,
        "lloc": 43,
        "mi": 73.57,
        "mIwoC": 44.78,
        "commentWeight": 28.79,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 400,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 400.27,
        "totalStructuralComplexity": 1600,
        "totalDataComplexity": 1.1,
        "totalSystemComplexity": 1601.1,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\PenitipanHewanController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\PenitipanHewan",
            "App\\Models\\PenitipanHewan",
            "App\\Models\\Hewan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Hewan",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\PenitipanHewan",
            "Illuminate\\Http\\Request",
            "App\\Models\\PenitipanHewan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 91,
        "vocabulary": 48,
        "volume": 508.23,
        "difficulty": 4.3,
        "effort": 2186.58,
        "level": 0.23,
        "bugs": 0.17,
        "time": 121,
        "intelligentContent": 118.13,
        "number_operators": 17,
        "number_operands": 74,
        "number_operators_unique": 5,
        "number_operands_unique": 43,
        "cloc": 6,
        "loc": 47,
        "lloc": 41,
        "mi": 71.62,
        "mIwoC": 45.33,
        "commentWeight": 26.28,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 529,
        "relativeDataComplexity": 0.24,
        "relativeSystemComplexity": 529.24,
        "totalStructuralComplexity": 2116,
        "totalDataComplexity": 0.96,
        "totalSystemComplexity": 2116.96,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ProfileController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\ProfileUpdateRequest",
            "Illuminate\\Support\\Facades\\Redirect",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Redirect"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 32,
        "vocabulary": 14,
        "volume": 121.84,
        "difficulty": 3.55,
        "effort": 431.96,
        "level": 0.28,
        "bugs": 0.04,
        "time": 24,
        "intelligentContent": 34.36,
        "number_operators": 6,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 9,
        "loc": 36,
        "lloc": 27,
        "mi": 88.87,
        "mIwoC": 53.9,
        "commentWeight": 34.97,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 196.27,
        "totalStructuralComplexity": 588,
        "totalDataComplexity": 0.8,
        "totalSystemComplexity": 588.8,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\RekamMedisController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\RekamMedis",
            "App\\Models\\RekamMedis",
            "Illuminate\\Http\\Request",
            "App\\Models\\RekamMedis",
            "App\\Models\\RekamMedis"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 7,
        "length": 6,
        "vocabulary": 2,
        "volume": 6,
        "difficulty": 0,
        "effort": 0,
        "level": 0.67,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 28,
        "loc": 53,
        "lloc": 25,
        "mi": 109.06,
        "mIwoC": 63.92,
        "commentWeight": 45.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0.86,
        "relativeSystemComplexity": 0.86,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\Auth\\LoginRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "authorize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "authenticate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ensureIsNotRateLimited",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "throttleKey",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Illuminate\\Validation\\ValidationException",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Illuminate\\Auth\\Events\\Lockout",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Illuminate\\Validation\\ValidationException",
            "Illuminate\\Support\\Str",
            "Illuminate\\Support\\Str"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 3,
        "length": 43,
        "vocabulary": 18,
        "volume": 179.31,
        "difficulty": 6.35,
        "effort": 1137.91,
        "level": 0.16,
        "bugs": 0.06,
        "time": 63,
        "intelligentContent": 28.25,
        "number_operators": 10,
        "number_operands": 33,
        "number_operators_unique": 5,
        "number_operands_unique": 13,
        "cloc": 21,
        "loc": 55,
        "lloc": 34,
        "mi": 91.29,
        "mIwoC": 50.41,
        "commentWeight": 40.88,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 196.27,
        "totalStructuralComplexity": 980,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 981.33,
        "package": "App\\Http\\Requests\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\ProfileUpdateRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest",
            "Illuminate\\Validation\\Rule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 8,
        "volume": 36,
        "difficulty": 0.79,
        "effort": 28.29,
        "level": 1.27,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 45.82,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 5,
        "loc": 13,
        "lloc": 8,
        "mi": 110.25,
        "mIwoC": 69.27,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 9.25,
        "package": "App\\Http\\Requests\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Models\\BookingKonsultasi",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dokter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 13,
        "volume": 59.21,
        "difficulty": 0.58,
        "effort": 34.54,
        "level": 1.71,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 101.5,
        "number_operators": 2,
        "number_operands": 14,
        "number_operators_unique": 1,
        "number_operands_unique": 12,
        "cloc": 2,
        "loc": 17,
        "lloc": 15,
        "mi": 87.14,
        "mIwoC": 61.8,
        "commentWeight": 25.34,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\Dokter",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rekamMedis",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 2,
        "length": 7,
        "vocabulary": 5,
        "volume": 16.25,
        "difficulty": 0.63,
        "effort": 10.16,
        "level": 1.6,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 26.01,
        "number_operators": 2,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 67.09,
        "mIwoC": 67.09,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 9.33,
        "package": "App\\Models\\",
        "pageRank": 0.05,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Models\\Hewan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "pemilik",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rekamMedis",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 2,
        "length": 11,
        "vocabulary": 8,
        "volume": 33,
        "difficulty": 0.64,
        "effort": 21.21,
        "level": 1.56,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 51.33,
        "number_operators": 2,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 64.93,
        "mIwoC": 64.93,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 9.33,
        "package": "App\\Models\\",
        "pageRank": 0.08,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "App\\Models\\Layanan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "rekamMedis",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0.5,
        "effort": 5.8,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 9,
        "lloc": 9,
        "mi": 71.59,
        "mIwoC": 71.59,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\PemeriksaanLab",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 13,
        "volume": 48.11,
        "difficulty": 0.5,
        "effort": 24.05,
        "level": 2,
        "bugs": 0.02,
        "time": 1,
        "intelligentContent": 96.21,
        "number_operators": 1,
        "number_operands": 12,
        "number_operators_unique": 1,
        "number_operands_unique": 12,
        "cloc": 1,
        "loc": 12,
        "lloc": 11,
        "mi": 86.99,
        "mIwoC": 65.37,
        "commentWeight": 21.62,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\PenitipanHewan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 14,
        "volume": 53.3,
        "difficulty": 0.5,
        "effort": 26.65,
        "level": 2,
        "bugs": 0.02,
        "time": 1,
        "intelligentContent": 106.61,
        "number_operators": 1,
        "number_operands": 13,
        "number_operators_unique": 1,
        "number_operands_unique": 13,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 65.06,
        "mIwoC": 65.06,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\RekamMedis",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "hewan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dokter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "layanan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 8,
        "volume": 36,
        "difficulty": 0.64,
        "effort": 23.14,
        "level": 1.56,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 56,
        "number_operators": 3,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 62.13,
        "mIwoC": 62.13,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 7.5,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "casts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dokter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hewan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "parents": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "implements": [],
        "lcom": 3,
        "length": 15,
        "vocabulary": 10,
        "volume": 49.83,
        "difficulty": 0.67,
        "effort": 33.22,
        "level": 1.5,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 74.74,
        "number_operators": 3,
        "number_operands": 12,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 16,
        "loc": 35,
        "lloc": 19,
        "mi": 103.39,
        "mIwoC": 60.08,
        "commentWeight": 43.31,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 15,
        "package": "App\\Models\\",
        "pageRank": 0.06,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AppServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "implements": [],
        "lcom": 2,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 8,
        "loc": 18,
        "lloc": 10,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Providers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\View\\Components\\AppLayout",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\View\\Component",
            "Illuminate\\View\\View"
        ],
        "parents": [
            "Illuminate\\View\\Component"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 114.24,
        "mIwoC": 78.06,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\View\\Components\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\View\\Components\\GuestLayout",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\View\\Component",
            "Illuminate\\View\\View"
        ],
        "parents": [
            "Illuminate\\View\\Component"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 114.24,
        "mIwoC": 78.06,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\View\\Components\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    }
]